import type { AppState } from './types';

export const BENEFICIOS_PADRAO = [
  '30% OFF em mão de obra',
  '15% OFF em acessórios',
  '6 trocas de película durante 12 meses',
  'Cashback exclusivo',
  'Programa Indique e Ganhe',
  'Consultoria gamer gratuita',
  'Limpeza gratuita de alto-falantes e microfones',
];

export const SERVICOS_TECHSOFT = [
  { title: 'Celulares', description: 'Troca de tela, bateria, conector de carga, tampa traseira, câmera, limpeza e diagnóstico.' },
  { title: 'Computadores e Notebooks', description: 'Formatação, upgrade de SSD, memória RAM, limpeza interna, manutenção e diagnóstico.' },
  { title: 'Videogames', description: 'Limpeza preventiva, manutenção, troca de analógicos, HDMI, superaquecimento e reparos.' },
  { title: 'Acessórios', description: 'Capinhas, películas, carregadores, cabos, fontes, fones e itens para proteção do seu aparelho.' },
];

export const STATUS_LABEL: Record<string, string> = {
  DISPONIVEL: 'AGUARDANDO CADASTRO',
  PENDENTE_ATIVACAO: 'PENDENTE DE ATIVAÇÃO',
  ATIVO: 'ATIVO',
  CANCELADO: 'CANCELADO',
  EXPIRADO: 'EXPIRADO',
};

export const STATUS_STYLE: Record<string, string> = {
  DISPONIVEL: 'border-yellow-300/30 bg-yellow-300/10 text-yellow-100',
  PENDENTE_ATIVACAO: 'border-sky-300/30 bg-sky-300/10 text-sky-100',
  ATIVO: 'border-tech-neon/40 bg-tech-neon/10 text-tech-neon',
  CANCELADO: 'border-red-300/30 bg-red-300/10 text-red-100',
  EXPIRADO: 'border-zinc-300/30 bg-zinc-300/10 text-zinc-100',
};

export const EMPTY_STATE: AppState = {
  empresas: [],
  clientes: [],
  techpasses: [],
  pending_activations: [],
  cashback_movements: [],
  indicacoes: [],
  utilizacoes: [],
  beneficios_servicos: [],
  solicitacoes: [],
  ofertas: [],
  leads: [],
  fight_core_indicacoes: [],
};

export function createInitialState(): AppState {
  const now = new Date().toISOString();
  const activatedAt = new Date();
  activatedAt.setMonth(activatedAt.getMonth() - 2);
  const expiresAt = new Date(activatedAt);
  expiresAt.setMonth(expiresAt.getMonth() + 12);

  const beneficiosServicos = [
    {
      id: 'bs-pelicula',
      nome: 'Troca de película TechSoft',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Películas',
      descricao: 'Troca de película inclusa para membros TechPass, limitada a 6 usos por ano.',
      valor_normal: 35,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 6,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Concluir somente após atendimento presencial. Reduz uma película do saldo.',
      created_at: now,
    },
    {
      id: 'bs-limpeza-gratis',
      nome: 'Limpeza gratuita',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Manutenção',
      descricao: 'Limpeza gratuita de alto-falantes, conectores e microfones.',
      valor_normal: 30,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Válido para avaliação rápida no balcão TechSoft.',
      created_at: now,
    },
    {
      id: 'bs-consultoria-gamer',
      nome: 'Consultoria gamer',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Videogames',
      descricao: 'Orientação para configuração, acessórios e cuidados com videogames.',
      valor_normal: 80,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Mediante agendamento e disponibilidade da equipe.',
      created_at: now,
    },
    ...[
      ['bs-tela', 'Troca de tela', 'TechSoft', 'Manutenção de celular', 'Troca de tela com condição especial para membros.', 220, 176, 20],
      ['bs-bateria', 'Troca de bateria', 'TechSoft', 'Manutenção de celular', 'Substituição de bateria com diagnóstico.', 180, 144, 20],
      ['bs-conector', 'Troca de conector de carga', 'TechSoft', 'Manutenção de celular', 'Reparo ou troca do conector de carga.', 160, 128, 20],
      ['bs-dados-android', 'Transferência de dados Android', 'TechSoft', 'Dados', 'Migração assistida de dados entre aparelhos Android.', 90, 63, 30],
      ['bs-dados-pc', 'Transferência de dados PC/Notebook', 'TechSoft', 'Dados', 'Cópia e organização de arquivos em computador ou notebook.', 120, 84, 30],
      ['bs-formatacao', 'Formatação', 'TechSoft', 'Computadores', 'Formatação com instalação básica e otimização.', 150, 105, 30],
      ['bs-limpeza-note', 'Limpeza interna de notebook', 'TechSoft', 'Computadores', 'Limpeza interna preventiva para notebook.', 180, 126, 30],
      ['bs-limpeza-game', 'Limpeza preventiva de videogame', 'TechSoft', 'Videogames', 'Limpeza preventiva para console e refrigeração.', 180, 126, 30],
      ['bs-analogico', 'Troca de analógico de controle', 'TechSoft', 'Videogames', 'Troca de analógico de controle compatível.', 120, 90, 25],
      ['bs-diagnostico', 'Diagnóstico técnico', 'TechSoft', 'Atendimento', 'Avaliação técnica inicial de aparelho.', 50, 0, 100],
      ['bs-ssd', 'Upgrade de SSD', 'TechSoft', 'Computadores', 'Instalação de SSD e migração básica.', 220, 165, 25],
      ['bs-ram', 'Upgrade de memória RAM', 'TechSoft', 'Computadores', 'Instalação ou expansão de memória RAM.', 160, 120, 25],
    ].map(([id, nome, _empresa, categoria, descricao, valorNormal, valorDesconto, percentual]) => ({
      id: id as string,
      nome: nome as string,
      tipo: 'servico_desconto' as const,
      empresa_id: 'emp-techsoft',
      categoria: categoria as string,
      descricao: descricao as string,
      valor_normal: Number(valorNormal),
      valor_desconto: Number(valorDesconto),
      percentual_desconto: Number(percentual),
      limite_uso: null,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Solicitar pelo dashboard e aguardar confirmação da empresa responsável.',
      created_at: now,
    })),
    {
      id: 'bs-super-geeks-aula',
      nome: 'Aula experimental',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-super-geeks',
      categoria: 'Educação',
      descricao: 'Aula experimental para conhecer a metodologia Super Geeks.',
      valor_normal: 120,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Sujeito à agenda da unidade parceira.',
      created_at: now,
    },
    {
      id: 'bs-fight-core-aula',
      nome: 'Aula experimental Fight Core',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-fight-core',
      categoria: 'Lutas',
      descricao: 'Aula experimental ou avaliação inicial na Fight Core.',
      valor_normal: 80,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Solicitar horário e aguardar confirmação.',
      created_at: now,
    },
  ];
  const ofertas = [
    {
      id: 'of-fc-mensal',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Mensal Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$199/mês',
      preco_techpass: 'R$179/mês',
      economia: 'R$20 por mês',
      descricao: 'Condição especial para membros TechPass treinarem na Fight Core.',
      regras: 'Válido para membros TechPass ativos. Sujeito à confirmação da Fight Core.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Tenho interesse',
      created_at: now,
    },
    {
      id: 'of-fc-semestral',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Semestral Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$1.194',
      preco_techpass: 'R$999',
      economia: 'R$195',
      descricao: 'Plano semestral com economia direta para membros TechPass.',
      regras: 'Pagamento e contratação definidos pela Fight Core.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Tenho interesse',
      created_at: now,
    },
    {
      id: 'of-fc-anual',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Anual Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$2.388',
      preco_techpass: 'R$1.908',
      economia: 'R$480',
      descricao: 'Plano anual com desconto exclusivo para membros TechPass.',
      regras: 'Pode liberar bônus de 6 meses se indicar 15 contatos e ao menos 1 fechar plano.',
      beneficio_extra: 'Possibilidade de ganhar bônus de 6 meses com indicações',
      status: 'ativo' as const,
      cta: 'Quero esta condição',
      created_at: now,
    },
    ...['Muay Thai', 'MMA', 'Jiu Jitsu', 'Jiu Jitsu Kids'].map((modalidade) => ({
      id: 'of-fc-aula-' + modalidade.toLowerCase().replace(/\s+/g, '-'),
      empresa_id: 'emp-fight-core',
      nome: 'Aula Grátis ' + modalidade,
      tipo: 'aula_gratis' as const,
      preco_normal: 'Aula experimental',
      preco_techpass: 'Grátis',
      economia: 'Experiência sem custo',
      descricao: modalidade === 'Jiu Jitsu Kids' ? 'Aula experimental para crianças.' : 'Experimente uma aula de ' + modalidade + ' na Fight Core.',
      regras: 'Solicitação sujeita à disponibilidade de agenda da Fight Core.',
      beneficio_extra: 'Lead direcionado para a modalidade escolhida',
      status: 'ativo' as const,
      cta: 'Solicitar aula',
      created_at: now,
    })),
    {
      id: 'of-sg-anual',
      empresa_id: 'emp-super-geeks',
      nome: 'Plano Anual Super Geeks',
      tipo: 'plano' as const,
      preco_normal: 'R$340/mês',
      preco_techpass: 'R$299/mês',
      economia: 'R$492 por ano',
      descricao: 'Condição especial para membros TechPass em plano anual Super Geeks.',
      regras: 'Válido para novas contratações pela Rede TechPass.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Quero esta condição',
      created_at: now,
    },
    {
      id: 'of-sg-renovacao',
      empresa_id: 'emp-super-geeks',
      nome: 'Renovação Super Geeks',
      tipo: 'renovacao' as const,
      preco_normal: 'Condição padrão',
      preco_techpass: 'Condição especial',
      economia: 'Renovação TechPass por 12 meses',
      descricao: 'Clientes que fecharem plano anual pela Rede TechPass ganham desconto garantido na próxima renovação e renovação gratuita do TechPass por mais 12 meses.',
      regras: 'Benefício aplicado conforme confirmação da Super Geeks.',
      beneficio_extra: 'Desconto na próxima renovação e TechPass renovado',
      status: 'ativo' as const,
      cta: 'Solicitar condição de renovação',
      created_at: now,
    },
  ];

  return {
    empresas: [
      {
        id: 'emp-techsoft',
        nome: 'TechSoft',
        categoria: 'Assistência técnica e acessórios',
        beneficio: '30% OFF em mão de obra, 15% OFF em acessórios, cashback e benefícios exclusivos.',
        status: 'ativa',
        created_at: now,
      },
      {
        id: 'emp-super-geeks',
        nome: 'Super Geeks',
        categoria: 'Educação e tecnologia',
        beneficio: 'Benefícios exclusivos para alunos e famílias parceiras.',
        status: 'ativa',
        created_at: now,
      },
      {
        id: 'emp-fight-core',
        nome: 'Fight Core',
        categoria: 'Academia de luta',
        beneficio: 'Condições especiais para membros TechPass.',
        status: 'ativa',
        created_at: now,
      },
    ],
    clientes: [
      {
        id: 'cli-maria',
        nome: 'Maria Eduarda Alves',
        cpf: '123.456.789-10',
        telefone: '(11) 99999-1111',
        email: 'maria@email.com',
        codigo_indicacao: 'TP-SG-000002-IND',
        created_at: activatedAt.toISOString(),
      },
    ],
    techpasses: [
      {
        id: 'tp-sg-000001',
        serial: 'TP-SG-000001',
        empresa_id: 'emp-super-geeks',
        cliente_id: null,
        status: 'DISPONIVEL',
        qr_code_url: '/techpass/TP-SG-000001',
        codigo_fisico: 'SG-7K2P',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
      {
        id: 'tp-sg-000002',
        serial: 'TP-SG-000002',
        empresa_id: 'emp-super-geeks',
        cliente_id: 'cli-maria',
        status: 'ATIVO',
        qr_code_url: '/techpass/TP-SG-000002',
        codigo_fisico: 'SG-4M9Q',
        codigo_usado: true,
        activated_at: activatedAt.toISOString(),
        expires_at: expiresAt.toISOString(),
        peliculas_restantes: 4,
        cashback_saldo: 30,
        codigo_indicacao: 'TP-SG-000002-IND',
        created_at: now,
      },
      {
        id: 'tp-fc-000001',
        serial: 'TP-FC-000001',
        empresa_id: 'emp-fight-core',
        cliente_id: null,
        status: 'DISPONIVEL',
        qr_code_url: '/techpass/TP-FC-000001',
        codigo_fisico: 'FC-5R6X',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
      {
        id: 'tp-fc-000002',
        serial: 'TP-FC-000002',
        empresa_id: 'emp-fight-core',
        cliente_id: null,
        status: 'CANCELADO',
        qr_code_url: '/techpass/TP-FC-000002',
        codigo_fisico: 'FC-2N4B',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
    ],
    pending_activations: [],
    cashback_movements: [
      {
        id: 'cash-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        tipo: 'credito',
        valor: 45,
        descricao: 'Cashback de boas-vindas TechPass',
        created_at: activatedAt.toISOString(),
      },
    ],
    indicacoes: [],
    utilizacoes: [
      {
        id: 'uti-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-techsoft',
        solicitacao_id: null,
        beneficio: 'Troca de película',
        status: 'concluida',
        observacao: 'Película aplicada no balcão TechSoft.',
        funcionario_responsavel: 'Atendimento TechSoft',
        created_at: activatedAt.toISOString(),
        completed_at: activatedAt.toISOString(),
      },
    ],
    beneficios_servicos: beneficiosServicos,
    ofertas,
    solicitacoes: [
      {
        id: 'sol-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-techsoft',
        beneficio_servico_id: 'bs-limpeza-note',
        tipo: 'servico_desconto',
        data_preferida: new Date().toISOString().slice(0, 10),
        horario_preferido: '14:00',
        observacao: 'Cliente deseja limpeza interna do notebook.',
        status: 'nova',
        funcionario_responsavel: '',
        data_solicitacao: now,
        data_conclusao: null,
        observacao_empresa: '',
      },
    ],
    leads: [
      {
        id: 'lead-maria-fc',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-fight-core',
        oferta_id: 'of-fc-anual',
        oferta_nome: 'Plano Anual Fight Core',
        telefone_cliente: '(11) 99999-1111',
        status: 'novo',
        observacao: 'Cliente demonstrou interesse pelo plano anual.',
        created_at: now,
      },
    ],
    fight_core_indicacoes: [],
  };
}
