import type { AppState } from './types';

export const BENEFICIOS_PADRAO = [
  '15% OFF em serviços técnicos',
  '15% OFF em acessórios',
  '6 trocas de película durante 12 meses',
  'Cashback exclusivo',
  'Programa Indique e Ganhe',
  'Consultoria gamer gratuita',
  'Limpeza gratuita de alto-falantes e microfones',
];

export const SERVICOS_TECHSOFT = [
  { title: 'Celulares', description: 'Troca de tela, bateria, conector de carga, tampa traseira, câmera, limpeza e diagnóstico.' },
  { title: 'Computadores e Notebooks', description: 'Formatação, upgrade de SSD, memória RAM, limpeza interna, manutenção e diagnóstico.' },
  { title: 'Videogames', description: 'Limpeza preventiva, manutenção, troca de analógicos, HDMI, superaquecimento e reparos.' },
  { title: 'Acessórios', description: 'Capinhas, películas, carregadores, cabos, fontes, fones e itens para proteção do seu aparelho.' },
];

export const STATUS_LABEL: Record<string, string> = {
  DISPONIVEL: 'AGUARDANDO CADASTRO',
  PENDENTE_ATIVACAO: 'PENDENTE DE ATIVAÇÃO',
  ATIVO: 'ATIVO',
  CANCELADO: 'CANCELADO',
  EXPIRADO: 'EXPIRADO',
};

export const STATUS_STYLE: Record<string, string> = {
  DISPONIVEL: 'border-yellow-300/30 bg-yellow-300/10 text-yellow-100',
  PENDENTE_ATIVACAO: 'border-sky-300/30 bg-sky-300/10 text-sky-100',
  ATIVO: 'border-tech-neon/40 bg-tech-neon/10 text-tech-neon',
  CANCELADO: 'border-red-300/30 bg-red-300/10 text-red-100',
  EXPIRADO: 'border-zinc-300/30 bg-zinc-300/10 text-zinc-100',
};

export const EMPTY_STATE: AppState = {
  empresas: [],
  parceiro_usuarios: [],
  clientes: [],
  techpasses: [],
  pending_activations: [],
  cashback_movements: [],
  cashback_settings: [],
  cashback_balances: [],
  cashback_transactions: [],
  indicacoes: [],
  utilizacoes: [],
  beneficios_servicos: [],
  solicitacoes: [],
  ofertas: [],
  leads: [],
  fight_core_indicacoes: [],
  techsoft_indicacoes: [],
  notifications: [],
  system_logs: [],
  budgets: [],
  budget_items: [],
  devices: [],
  gift_links: [],
  digital_links: [],
};

export function createInitialState(): AppState {
  const now = new Date().toISOString();
  const noCashback = {
    cashback_ativo: false,
    cashback_tipo: 'sem_cashback' as const,
    cashback_valor: null,
    cashback_limite: null,
    cashback_regras: '',
    cashback_descricao_cliente: '',
  };
  const activatedAt = new Date();
  activatedAt.setMonth(activatedAt.getMonth() - 2);
  const expiresAt = new Date(activatedAt);
  expiresAt.setMonth(expiresAt.getMonth() + 12);

  const devices = [
    {
      id: 'dev-iphone-11',
      marca: 'Apple',
      modelo: 'iPhone 11',
      categoria: 'Smartphone',
      imagem_url: 'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=900&q=80',
      especificacoes: 'Tela Liquid Retina HD 6,1", chip A13 Bionic, Face ID, câmera dupla 12 MP, conector Lightning.',
      servicos_sugeridos: ['Troca de tela', 'Troca de bateria', 'Troca de conector de carga', 'Diagnóstico técnico', 'Película premium'],
      pecas_sugeridas: [
        { nome: 'Tela compatível iPhone 11', categoria: 'Tela', preco_estimado: 390, disponibilidade: 'pronta_entrega' as const, link_sugestao: 'https://lista.mercadolivre.com.br/tela-iphone-11' },
        { nome: 'Bateria iPhone 11', categoria: 'Bateria', preco_estimado: 220, disponibilidade: 'encomenda' as const, link_sugestao: 'https://lista.mercadolivre.com.br/bateria-iphone-11' },
      ],
      created_at: now,
    },
    {
      id: 'dev-samsung-a54',
      marca: 'Samsung',
      modelo: 'Galaxy A54',
      categoria: 'Smartphone',
      imagem_url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=80',
      especificacoes: 'Tela Super AMOLED 6,4", 5G, câmera tripla, USB-C, bateria 5000 mAh.',
      servicos_sugeridos: ['Troca de display', 'Troca de tampa traseira', 'Troca de conector USB-C', 'Limpeza interna', 'Diagnóstico técnico'],
      pecas_sugeridas: [
        { nome: 'Display Samsung Galaxy A54', categoria: 'Display', preco_estimado: 520, disponibilidade: 'mercado_livre' as const, link_sugestao: 'https://lista.mercadolivre.com.br/display-samsung-a54' },
        { nome: 'Conector de carga Galaxy A54', categoria: 'Conector', preco_estimado: 120, disponibilidade: 'encomenda' as const, link_sugestao: 'https://lista.mercadolivre.com.br/conector-carga-galaxy-a54' },
      ],
      created_at: now,
    },
    {
      id: 'dev-notebook-dell',
      marca: 'Dell',
      modelo: 'Notebook Inspiron',
      categoria: 'Notebook',
      imagem_url: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=900&q=80',
      especificacoes: 'Notebook linha Inspiron, armazenamento SSD/HD conforme versão, memória RAM expansível, Windows.',
      servicos_sugeridos: ['Formatação', 'Upgrade de SSD', 'Upgrade de memória RAM', 'Limpeza interna', 'Diagnóstico técnico'],
      pecas_sugeridas: [
        { nome: 'SSD SATA/NVMe 480GB', categoria: 'Armazenamento', preco_estimado: 260, disponibilidade: 'pronta_entrega' as const, link_sugestao: 'https://lista.mercadolivre.com.br/ssd-480gb' },
        { nome: 'Memória RAM notebook DDR4 8GB', categoria: 'Memória', preco_estimado: 180, disponibilidade: 'mercado_livre' as const, link_sugestao: 'https://lista.mercadolivre.com.br/memoria-ram-notebook-ddr4-8gb' },
      ],
      created_at: now,
    },
  ];

  const beneficiosServicos = [
    {
      id: 'bs-pelicula',
      nome: 'Troca de película TechSoft',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Películas',
      descricao: 'Troca de película inclusa para membros TechPass, limitada a 6 usos por ano.',
      valor_normal: 35,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 6,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Concluir somente após atendimento presencial. Reduz uma película do saldo.',
      created_at: now,
    },
    {
      id: 'bs-limpeza-gratis',
      nome: 'Limpeza gratuita',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Manutenção',
      descricao: 'Limpeza gratuita de alto-falantes, conectores e microfones.',
      valor_normal: 30,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Válido para avaliação rápida no balcão TechSoft.',
      created_at: now,
    },
    {
      id: 'bs-consultoria-gamer',
      nome: 'Consultoria gamer',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-techsoft',
      categoria: 'Videogames',
      descricao: 'Orientação para configuração, acessórios e cuidados com videogames.',
      valor_normal: 80,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Mediante agendamento e disponibilidade da equipe.',
      created_at: now,
    },
    ...[
      ['bs-tela', 'Troca de tela', 'TechSoft', 'Manutenção de celular', 'Troca de tela com condição especial para membros.', 220, 176, 20],
      ['bs-bateria', 'Troca de bateria', 'TechSoft', 'Manutenção de celular', 'Substituição de bateria com diagnóstico.', 180, 144, 20],
      ['bs-conector', 'Troca de conector de carga', 'TechSoft', 'Manutenção de celular', 'Reparo ou troca do conector de carga.', 160, 128, 20],
      ['bs-dados-android', 'Transferência de dados Android', 'TechSoft', 'Dados', 'Migração assistida de dados entre aparelhos Android.', 90, 63, 30],
      ['bs-dados-pc', 'Transferência de dados PC/Notebook', 'TechSoft', 'Dados', 'Cópia e organização de arquivos em computador ou notebook.', 120, 84, 30],
      ['bs-formatacao', 'Formatação', 'TechSoft', 'Computadores', 'Formatação com instalação básica e otimização.', 150, 105, 30],
      ['bs-limpeza-note', 'Limpeza interna de notebook', 'TechSoft', 'Computadores', 'Limpeza interna preventiva para notebook.', 180, 126, 30],
      ['bs-limpeza-game', 'Limpeza preventiva de videogame', 'TechSoft', 'Videogames', 'Limpeza preventiva para console e refrigeração.', 180, 126, 30],
      ['bs-analogico', 'Troca de analógico de controle', 'TechSoft', 'Videogames', 'Troca de analógico de controle compatível.', 120, 90, 25],
      ['bs-diagnostico', 'Diagnóstico técnico', 'TechSoft', 'Atendimento', 'Avaliação técnica inicial de aparelho.', 50, 0, 100],
      ['bs-ssd', 'Upgrade de SSD', 'TechSoft', 'Computadores', 'Instalação de SSD e migração básica.', 220, 165, 25],
      ['bs-ram', 'Upgrade de memória RAM', 'TechSoft', 'Computadores', 'Instalação ou expansão de memória RAM.', 160, 120, 25],
    ].map(([id, nome, _empresa, categoria, descricao, valorNormal, valorDesconto, percentual]) => ({
      id: id as string,
      nome: nome as string,
      tipo: 'servico_desconto' as const,
      empresa_id: 'emp-techsoft',
      categoria: categoria as string,
      descricao: descricao as string,
      valor_normal: Number(valorNormal),
      valor_desconto: Number(valorDesconto),
      percentual_desconto: Number(percentual),
      limite_uso: null,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Solicitar pelo dashboard e aguardar confirmação da empresa responsável.',
      created_at: now,
    })),
    {
      id: 'bs-super-geeks-aula',
      nome: 'Aula experimental',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-super-geeks',
      categoria: 'Educação',
      descricao: 'Aula experimental para conhecer a metodologia Super Geeks.',
      valor_normal: 120,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Sujeito à agenda da unidade parceira.',
      created_at: now,
    },
    {
      id: 'bs-fight-core-aula',
      nome: 'Aula experimental Fight Core',
      tipo: 'beneficio' as const,
      empresa_id: 'emp-fight-core',
      categoria: 'Lutas',
      descricao: 'Aula experimental ou avaliação inicial na Fight Core.',
      valor_normal: 80,
      valor_desconto: 0,
      percentual_desconto: 100,
      limite_uso: 1,
      validade: null,
      status: 'ativo' as const,
      regras_uso: 'Solicitar horário e aguardar confirmação.',
      created_at: now,
    },
  ];
  const ofertas = [
    {
      id: 'of-fc-mensal',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Mensal Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$199/mês',
      preco_techpass: 'R$179/mês',
      economia: 'R$20 por mês',
      descricao: 'Condição especial para membros TechPass treinarem na Fight Core.',
      regras: 'Válido para membros TechPass ativos. Sujeito à confirmação da Fight Core.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Tenho interesse',
      descricao_completa: 'Plano mensal Fight Core com condição especial para membros TechPass.',
      validade: null,
      origem: 'admin' as const,
      cashback_ativo: true,
      cashback_tipo: 'valor_fixo' as const,
      cashback_valor: 14.83,
      cashback_limite: 178,
      cashback_regras: 'Cashback proporcional ao plano mensal após confirmação da Fight Core.',
      cashback_descricao_cliente: 'Você pode ganhar R$14,83 em cashback nesta oferta.',
      created_at: now,
    },
    {
      id: 'of-fc-semestral',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Semestral Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$1.194',
      preco_techpass: 'R$999',
      economia: 'R$195',
      descricao: 'Plano semestral com economia direta para membros TechPass.',
      regras: 'Pagamento e contratação definidos pela Fight Core.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Tenho interesse',
      descricao_completa: 'Plano semestral Fight Core com economia direta para membros TechPass.',
      validade: null,
      origem: 'admin' as const,
      cashback_ativo: true,
      cashback_tipo: 'proporcional' as const,
      cashback_valor: 89,
      cashback_limite: 178,
      cashback_regras: 'Cashback proporcional ao período contratado.',
      cashback_descricao_cliente: 'Cashback proporcional liberado após confirmação da contratação.',
      created_at: now,
    },
    {
      id: 'of-fc-anual',
      empresa_id: 'emp-fight-core',
      nome: 'Plano Anual Fight Core',
      tipo: 'plano' as const,
      preco_normal: 'R$2.388',
      preco_techpass: 'R$1.908',
      economia: 'R$480',
      descricao: 'Plano anual com desconto exclusivo para membros TechPass.',
      regras: 'Pode liberar bônus de 6 meses se indicar 15 contatos e ao menos 1 fechar plano.',
      beneficio_extra: 'Possibilidade de ganhar bônus de 6 meses com indicações',
      status: 'ativo' as const,
      cta: 'Quero esta condição',
      descricao_completa: 'Plano anual Fight Core com desconto e possibilidade de bônus de 6 meses via indicações.',
      validade: null,
      origem: 'admin' as const,
      cashback_ativo: true,
      cashback_tipo: 'mensalidade' as const,
      cashback_valor: 178,
      cashback_limite: 178,
      cashback_regras: 'Equivalente a 1 mensalidade em benefícios após contratar o plano anual pela Rede TechPass.',
      cashback_descricao_cliente: 'Cashback TechPass: R$178, equivalente a 1 mês de mensalidade em benefícios.',
      created_at: now,
    },
    ...['Muay Thai', 'MMA', 'Jiu Jitsu', 'Jiu Jitsu Kids'].map((modalidade) => ({
      id: 'of-fc-aula-' + modalidade.toLowerCase().replace(/\s+/g, '-'),
      empresa_id: 'emp-fight-core',
      nome: 'Aula Grátis ' + modalidade,
      tipo: 'aula_gratis' as const,
      preco_normal: 'Aula experimental',
      preco_techpass: 'Grátis',
      economia: 'Experiência sem custo',
      descricao: modalidade === 'Jiu Jitsu Kids' ? 'Aula experimental para crianças.' : 'Experimente uma aula de ' + modalidade + ' na Fight Core.',
      regras: 'Solicitação sujeita à disponibilidade de agenda da Fight Core.',
      beneficio_extra: 'Lead direcionado para a modalidade escolhida',
      status: 'ativo' as const,
      cta: 'Solicitar aula',
      descricao_completa: modalidade === 'Jiu Jitsu Kids' ? 'Aula experimental para crianças na Fight Core.' : 'Aula experimental de ' + modalidade + ' na Fight Core.',
      validade: null,
      origem: 'admin' as const,
      ...noCashback,
      created_at: now,
    })),
    {
      id: 'of-sg-anual',
      empresa_id: 'emp-super-geeks',
      nome: 'Plano Anual Super Geeks',
      tipo: 'plano' as const,
      preco_normal: 'R$340/mês',
      preco_techpass: 'R$299/mês',
      economia: 'R$492 por ano',
      descricao: 'Condição especial para membros TechPass em plano anual Super Geeks.',
      regras: 'Válido para novas contratações pela Rede TechPass.',
      beneficio_extra: 'Condição especial para membros TechPass',
      status: 'ativo' as const,
      cta: 'Quero esta condição',
      descricao_completa: 'Plano anual Super Geeks com condição especial para famílias TechPass.',
      validade: null,
      origem: 'admin' as const,
      cashback_ativo: true,
      cashback_tipo: 'valor_fixo' as const,
      cashback_valor: 299,
      cashback_limite: 299,
      cashback_regras: 'Cashback configurável para plano anual Super Geeks após fechamento confirmado.',
      cashback_descricao_cliente: 'Cashback ou benefício equivalente a uma mensalidade, conforme regra da Super Geeks.',
      created_at: now,
    },
    {
      id: 'of-sg-renovacao',
      empresa_id: 'emp-super-geeks',
      nome: 'Renovação Super Geeks',
      tipo: 'renovacao' as const,
      preco_normal: 'Condição padrão',
      preco_techpass: 'Condição especial',
      economia: 'Renovação TechPass por 12 meses',
      descricao: 'Clientes que fecharem plano anual pela Rede TechPass ganham desconto garantido na próxima renovação e renovação gratuita do TechPass por mais 12 meses.',
      regras: 'Benefício aplicado conforme confirmação da Super Geeks.',
      beneficio_extra: 'Desconto na próxima renovação e TechPass renovado',
      status: 'ativo' as const,
      cta: 'Solicitar condição de renovação',
      descricao_completa: 'Condição de renovação para clientes que contrataram pela Rede TechPass.',
      validade: null,
      origem: 'admin' as const,
      ...noCashback,
      created_at: now,
    },
  ];

  return {
    empresas: [
      {
        id: 'emp-techsoft',
        nome: 'TechSoft',
        categoria: 'Assistência técnica e acessórios',
        beneficio: '15% OFF em serviços técnicos, 15% OFF em acessórios, cashback e benefícios exclusivos.',
        status: 'ativa',
        telefone: '(11) 4002-8922',
        whatsapp: '(11) 99999-0000',
        email: 'contato@techsoft.com.br',
        endereco: 'Atendimento presencial TechSoft',
        descricao: 'Assistência técnica, acessórios e central operacional TechPass.',
        instagram: '@techsoft',
        logo_url: '',
        created_at: now,
      },
      {
        id: 'emp-super-geeks',
        nome: 'Super Geeks',
        categoria: 'Educação e tecnologia',
        beneficio: 'Benefícios exclusivos para alunos e famílias parceiras.',
        status: 'ativa',
        telefone: '(11) 3000-1000',
        whatsapp: '(11) 98888-1000',
        email: 'parcerias@supergeeks.com.br',
        endereco: 'Unidade parceira Super Geeks',
        descricao: 'Educação em tecnologia e programação para crianças e jovens.',
        instagram: '@supergeeks',
        logo_url: '',
        created_at: now,
      },
      {
        id: 'emp-fight-core',
        nome: 'Fight Core',
        categoria: 'Academia de luta',
        beneficio: 'Condições especiais para membros TechPass.',
        status: 'ativa',
        telefone: '(11) 3000-2000',
        whatsapp: '(11) 97777-2000',
        email: 'contato@fightcore.com.br',
        endereco: 'Academia Fight Core',
        descricao: 'Muay Thai, Jiu Jitsu, MMA e treinos para adultos e crianças.',
        instagram: '@fightcore',
        logo_url: '',
        created_at: now,
      },
    ],
    parceiro_usuarios: [
      { id: 'par-techsoft', nome: 'Parceiro TechSoft', email: 'techsoft@parceiro.com', senha: '123456', empresa_id: 'emp-techsoft', tipo_acesso: 'parceiro', created_at: now },
      { id: 'par-super-geeks', nome: 'Parceiro Super Geeks', email: 'supergeeks@parceiro.com', senha: '123456', empresa_id: 'emp-super-geeks', tipo_acesso: 'parceiro', created_at: now },
      { id: 'par-fight-core', nome: 'Parceiro Fight Core', email: 'fightcore@parceiro.com', senha: '123456', empresa_id: 'emp-fight-core', tipo_acesso: 'parceiro', created_at: now },
    ],
    clientes: [
      {
        id: 'cli-maria',
        nome: 'Maria Eduarda Alves',
        cpf: '123.456.789-10',
        telefone: '(11) 99999-1111',
        email: 'maria@email.com',
        codigo_indicacao: 'TP-SG-000002-IND',
        created_at: activatedAt.toISOString(),
      },
    ],
    techpasses: [
      {
        id: 'tp-sg-000001',
        serial: 'TP-SG-000001',
        empresa_id: 'emp-super-geeks',
        cliente_id: null,
        status: 'DISPONIVEL',
        qr_code_url: '/techpass/TP-SG-000001',
        codigo_fisico: 'SG-7K2P',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
      {
        id: 'tp-sg-000002',
        serial: 'TP-SG-000002',
        empresa_id: 'emp-super-geeks',
        cliente_id: 'cli-maria',
        status: 'ATIVO',
        qr_code_url: '/techpass/TP-SG-000002',
        codigo_fisico: 'SG-4M9Q',
        codigo_usado: true,
        activated_at: activatedAt.toISOString(),
        expires_at: expiresAt.toISOString(),
        peliculas_restantes: 4,
        cashback_saldo: 30,
        codigo_indicacao: 'TP-SG-000002-IND',
        created_at: now,
      },
      {
        id: 'tp-fc-000001',
        serial: 'TP-FC-000001',
        empresa_id: 'emp-fight-core',
        cliente_id: null,
        status: 'DISPONIVEL',
        qr_code_url: '/techpass/TP-FC-000001',
        codigo_fisico: 'FC-5R6X',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
      {
        id: 'tp-fc-000002',
        serial: 'TP-FC-000002',
        empresa_id: 'emp-fight-core',
        cliente_id: null,
        status: 'CANCELADO',
        qr_code_url: '/techpass/TP-FC-000002',
        codigo_fisico: 'FC-2N4B',
        codigo_usado: false,
        activated_at: null,
        expires_at: null,
        peliculas_restantes: 6,
        cashback_saldo: 0,
        codigo_indicacao: null,
        created_at: now,
      },
    ],
    pending_activations: [],
    cashback_movements: [
      {
        id: 'cash-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        tipo: 'credito',
        valor: 45,
        descricao: 'Cashback de boas-vindas TechPass',
        created_at: activatedAt.toISOString(),
      },
    ],
    cashback_settings: [
      {
        id: 'cashset-techsoft',
        empresa_id: 'emp-techsoft',
        ativo: true,
        valor_minimo: 250,
        tipo_calculo: 'percentual',
        limite_maximo: 100,
        regras_uso: 'Compras acima de R$250 geram cashback cumulativo até R$100. Não pode ser convertido em dinheiro.',
        status: 'ativo',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'cashset-fight-core',
        empresa_id: 'emp-fight-core',
        ativo: true,
        valor_minimo: 0,
        tipo_calculo: 'oferta_especifica',
        limite_maximo: 178,
        regras_uso: 'Planos Fight Core podem gerar cashback por oferta, inclusive equivalente a 1 mensalidade.',
        status: 'ativo',
        created_at: now,
        updated_at: now,
      },
      {
        id: 'cashset-super-geeks',
        empresa_id: 'emp-super-geeks',
        ativo: true,
        valor_minimo: 0,
        tipo_calculo: 'oferta_especifica',
        limite_maximo: 299,
        regras_uso: 'Cashback apenas no plano anual ou benefício equivalente definido pela Super Geeks.',
        status: 'ativo',
        created_at: now,
        updated_at: now,
      },
    ],
    cashback_balances: [
      {
        id: 'cashbal-maria-techsoft',
        cliente_id: 'cli-maria',
        empresa_id: 'emp-techsoft',
        saldo_disponivel: 68.5,
        saldo_pendente: 0,
        limite_maximo: 100,
        updated_at: now,
      },
      {
        id: 'cashbal-maria-fc',
        cliente_id: 'cli-maria',
        empresa_id: 'emp-fight-core',
        saldo_disponivel: 0,
        saldo_pendente: 178,
        limite_maximo: 178,
        updated_at: now,
      },
    ],
    cashback_transactions: [
      {
        id: 'cashtx-maria-techsoft',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-techsoft',
        oferta_id: null,
        lead_id: null,
        tipo: 'credito',
        valor: 68.5,
        status: 'disponivel',
        descricao: 'TechCash TechSoft gerado em compra acima de R$250.',
        valor_compra: 685,
        created_at: activatedAt.toISOString(),
      },
      {
        id: 'cashtx-maria-fc',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-fight-core',
        oferta_id: 'of-fc-anual',
        lead_id: 'lead-maria-fc',
        tipo: 'credito',
        valor: 178,
        status: 'pendente',
        descricao: 'Cashback gerado pelo Plano Anual Fight Core.',
        valor_compra: 2268,
        created_at: now,
      },
    ],
    indicacoes: [],
    utilizacoes: [
      {
        id: 'uti-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-techsoft',
        solicitacao_id: null,
        beneficio: 'Troca de película',
        status: 'concluida',
        observacao: 'Película aplicada no balcão TechSoft.',
        funcionario_responsavel: 'Atendimento TechSoft',
        created_at: activatedAt.toISOString(),
        completed_at: activatedAt.toISOString(),
      },
    ],
    beneficios_servicos: beneficiosServicos,
    ofertas,
    solicitacoes: [
      {
        id: 'sol-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-techsoft',
        beneficio_servico_id: 'bs-limpeza-note',
        tipo: 'servico_desconto',
        data_preferida: new Date().toISOString().slice(0, 10),
        horario_preferido: '14:00',
        observacao: 'Cliente deseja limpeza interna do notebook.',
        status: 'nova',
        funcionario_responsavel: '',
        data_solicitacao: now,
        data_conclusao: null,
        observacao_empresa: '',
      },
    ],
    leads: [
      {
        id: 'lead-maria-fc',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        empresa_id: 'emp-fight-core',
        oferta_id: 'of-fc-anual',
        oferta_nome: 'Plano Anual Fight Core',
        telefone_cliente: '(11) 99999-1111',
        status: 'novo',
        observacao: 'Cliente demonstrou interesse pelo plano anual.',
        created_at: now,
      },
    ],
    fight_core_indicacoes: [],
    techsoft_indicacoes: [
      {
        id: 'tsind-maria-1',
        cliente_id: 'cli-maria',
        techpass_id: 'tp-sg-000002',
        nome_indicado: 'Carlos Henrique',
        telefone_indicado: '(11) 98888-2222',
        observacao: 'Interessado em película e capinha.',
        status: 'em_contato',
        valor_compra: 0,
        gerou_brinde: false,
        created_at: now,
      },
    ],
    notifications: [
      {
        id: 'not-cli-ativado',
        user_id: 'cli-maria',
        empresa_id: null,
        tipo_usuario: 'cliente',
        titulo: 'TechPass ativado',
        descricao: 'Seu TechPass esta ativo e pronto para usar na Rede TechPass.',
        tipo: 'sucesso',
        url: '/cliente/dashboard',
        lida: false,
        created_at: activatedAt.toISOString(),
      },
      {
        id: 'not-cli-oferta',
        user_id: 'cli-maria',
        empresa_id: 'emp-fight-core',
        tipo_usuario: 'cliente',
        titulo: 'Oferta Fight Core disponivel',
        descricao: 'Plano anual com economia estimada de R$480 e possibilidade de bonus por indicacao.',
        tipo: 'informacao',
        url: '/cliente/dashboard',
        lida: false,
        created_at: now,
      },
      {
        id: 'not-cli-cashback',
        user_id: 'cli-maria',
        empresa_id: 'emp-techsoft',
        tipo_usuario: 'cliente',
        titulo: 'Cashback liberado',
        descricao: 'Voce tem TechCash disponivel para usar em beneficios TechSoft.',
        tipo: 'sucesso',
        url: '/cliente/dashboard',
        lida: true,
        created_at: now,
      },
      {
        id: 'not-par-fc-lead',
        user_id: 'par-fight-core',
        empresa_id: 'emp-fight-core',
        tipo_usuario: 'parceiro',
        titulo: 'Novo lead recebido',
        descricao: 'Maria Eduarda demonstrou interesse no Plano Anual Fight Core.',
        tipo: 'informacao',
        url: '/parceiro/dashboard',
        lida: false,
        created_at: now,
      },
      {
        id: 'not-par-techsoft-cashback',
        user_id: 'par-techsoft',
        empresa_id: 'emp-techsoft',
        tipo_usuario: 'parceiro',
        titulo: 'Cashback aguardando aprovacao',
        descricao: 'Revise as movimentacoes de TechCash pendentes da TechSoft.',
        tipo: 'alerta',
        url: '/parceiro/dashboard',
        lida: false,
        created_at: now,
      },
      {
        id: 'not-admin-oferta',
        user_id: null,
        empresa_id: 'emp-fight-core',
        tipo_usuario: 'admin',
        titulo: 'Oferta aguardando aprovacao',
        descricao: 'Parceiros podem publicar ofertas que precisam de revisao do administrador.',
        tipo: 'alerta',
        url: '/admin',
        lida: false,
        created_at: now,
      },
      {
        id: 'not-admin-log',
        user_id: null,
        empresa_id: null,
        tipo_usuario: 'admin',
        titulo: 'Backup concluido',
        descricao: 'Rotina de backup demo concluida sem erros.',
        tipo: 'sucesso',
        url: '/admin',
        lida: true,
        created_at: now,
      },
    ],
    system_logs: [
      {
        id: 'log-backup',
        nivel: 'info',
        usuario: 'Sistema',
        empresa: 'TechPass',
        pagina: '/admin',
        descricao: 'Backup concluido com sucesso.',
        stacktrace: '',
        created_at: now,
      },
      {
        id: 'log-auth-warning',
        nivel: 'warning',
        usuario: 'visitante',
        empresa: 'TechPass',
        pagina: '/login',
        descricao: 'Tentativa de login sem TechPass ativo correspondente.',
        stacktrace: '',
        created_at: now,
      },
      {
        id: 'log-qrcode-error',
        nivel: 'error',
        usuario: 'Sistema',
        empresa: 'TechSoft',
        pagina: '/techpass/TP-INVALIDO',
        descricao: 'QR Code solicitado para serial inexistente.',
        stacktrace: 'NotFoundError: TechPass serial not found',
        created_at: now,
      },
    ],
    budgets: [
      {
        id: 'bud-0001',
        numero: 'TS-2026-0001',
        data_orcamento: new Date().toISOString().slice(0, 10),
        previsao_entrega: '',
        tecnico_responsavel: 'Fabiano Oliveira / Matheus Schipmann',
        aos_cuidados_de: 'Maria Eduarda',
        cliente_nome: 'Maria Eduarda',
        cliente_documento: '123.456.789-10',
        cliente_endereco: 'Rua Exemplo, 100',
        cliente_cep: '88101-000',
        cliente_cidade: 'Sao Jose',
        cliente_estado: 'SC',
        cliente_telefone: '(48) 99999-0000',
        cliente_email: 'maria@email.com',
        device_id: 'dev-iphone-11',
        device_modelo: 'Apple iPhone 11',
        device_serial: 'SN-MARIA-001',
        device_specs: devices[0].especificacoes,
        device_image_url: devices[0].imagem_url,
        public_notes: 'Orçamento sujeito à confirmação técnica após abertura do aparelho.',
        garantia_texto: 'Este servico possui garantia de 6 meses a partir da data de conclusao.\n\nA garantia nao cobre danos causados por mau uso, quedas, oscilacoes eletricas, liquidos ou intervencao de terceiros.',
        subtotal: 350,
        total: 350,
        status: 'rascunho',
        created_at: now,
        updated_at: now,
      },
    ],
    budget_items: [
      {
        id: 'bitem-0001',
        budget_id: 'bud-0001',
        item_numero: 1,
        nome: 'Troca de tela iPhone - serviço técnico e componente',
        quantidade: 1,
        valor_unitario: 350,
        subtotal: 350,
        tipo: 'servico',
        disponibilidade: 'pronta_entrega',
        fornecedor_url: '',
        created_at: now,
      },
    ],
    devices,
    gift_links: [
      {
        id: 'gift-demo-0001',
        token: 'BRINDE-DEMO-001',
        cliente_nome: '',
        cliente_telefone: '',
        cliente_email: '',
        status: 'disponivel',
        premio: null,
        created_at: now,
        used_at: null,
        redeemed_at: null,
      },
    ],
    digital_links: [],
  };
}
